#Hugo configuration
title = "Name"
baseURL = "https:\/\/www.drf.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758397"
subfolder = ""
firstpartycookies = true
cookiedomain = "drf.com"
